### ISSUE TITLE
Is the resulting velocity vector in per-pixel or per-100-pixel unit?

### ISSUE THREAD

**Issue by zhuokaizhao** [erizmr/UnLiteFlowNet-PIV#1]
Dear Mingrui,

First of all, thank you for the great work. It is not an issue, more like a question. In your paper I saw you were using AEE per 100 pixels when comparing with other methods. Does it imply that your model naturally gives out velocity vectors in the unit of per 100 pixels? Or does it still give out results in per-pixel unit, and you did some linear interpolation after it?
 
Thanks,
Zhuokai

**Comment by erizmr** [comment]
Hi Zhuokai,

Thanks for your interest in this work! 
The model gives out dense velocities in per-pixel unit. There is no further interpolation on the output results. The AEE per 100 pixels metric used in the paper is just for the sake of easier comparision (because the value of AEE per-pixel is relatively quite small). Sorry for the confusion made in this part.

Regards,
Mingrui

**Comment by zhuokaizhao** [comment]
Thank you for the clarification!
